/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as recycleChianSol from './RecycleChian.sol'
export type { recycleChianSol }
export type { RecycleChain } from './RecycleChain'
