version: '3.8'

services:
  db:
    container_name: recycle_chain_db
    image: postgres
    restart: always
    ports:
      - 2002:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - db_data_recycle_chain_workshop:/var/lib/postgresql/data
volumes:
  db_data_recycle_chain_workshop:
